### ISSUE TITLE
chore: Confirm Android Build Chain Versions

### ISSUE THREAD

**Issue by tomarra** [VeryGoodOpenSource/very_good_templates#108]
**Description**

With Flutter 3.22 there are new updates/requirements on the Android build chain which can be found [here](https://docs.google.com/document/d/1qeeM5QG-jiafttSgvc7yvC19IDRggFFZQTktBVxL6sI/edit?resourcekey=0-HLEAiBOMxAlQxDs-mEeffw). We need to make sure we are up to date with these so we don't end up with errors in the next major release.

**Requirements**

- [ ] Ensure that Gradle is at 7.0.2 or above
- [ ] Ensure that AGP is at 7.0.0 or above
- [ ] Ensure that Java is at 11 or above
- [ ] Ensure that Kotlin is at 1.5.0 or above

**Comment by alestiago** [comment]
| Application              | JVM version | Gradle version | AGP version | Kotlin version |
|--------------------------|-------------|----------------|-------------|----------------|
| very_good_core           |             |                |             |                |
| very_good_flame_game     |             |                |             |                |
| very_good_flutter_plugin |             |                |             |                |
| very_good_wear_app       |             |                |             |                |

**Comment by tomarra** [comment]
@tomarra to create new issues to tackle the updates.

- Java updates across all
- Flame Game Kotlin Version needs to go up 
- Flutter Plugin Example updates to get in line with everything else
- Flutter Pugin and Example app need to get updated to recommended plugins DSL.

**Comment by tomarra** [comment]
Child tickets have been created. Closing this ticket out as done.
