### ISSUE TITLE
chore: Remove V1 Embedding from Plugin Template

### ISSUE THREAD

**Issue by tomarra** [VeryGoodOpenSource/very_good_templates#109]
**Description**

This is a cleanup task based on the Flutter 3.22 release notes. 

"we recommend that plugin authors release updated versions of their plugins with the v1 code removed as soon as possible, to avoid breakage in future versions of Flutter".

**Requirements**

- [ ] No functional changes to the code
- [ ] The V1 embedding code is removed from the plugin template

**Comment by alestiago** [comment]
Referencing:
- [What's new in Flutter 3.22](https://medium.com/flutter/whats-new-in-flutter-3-22-fbde6c164fe3)
- [Supporting the new Android plugins APIs](https://docs.flutter.dev/release/breaking-changes/plugin-api-migration) migration guide
- [Relevant Flutter commit](https://github.com/flutter/flutter/pull/144726)

**Comment by alestiago** [comment]
Moving this to "In Review", would like to get @wolfenrain's pair of eyes before closing.

**Comment by tomarra** [comment]
Assigning myself and @wolfenrain to this so we can be the second pair of eyes on this and confirm that we don't need any changes here

**Comment by tomarra** [comment]
Agree with the comments from @alestiago. Going to close this out as completed.
