### ISSUE TITLE
ci: publish workflow fails to publish

### ISSUE THREAD

**Issue by alestiago** [VeryGoodOpenSource/very_good_templates#147]
**Description**

The [`publish_very_good_core` workflow](https://github.com/VeryGoodOpenSource/very_good_templates/blob/main/.github/workflows/publish_very_good_core.yaml) fails to complete successfully with:

```txt
You must be logged in to publish.
Run 'mason login' to log in and try again.
```

See the[ full action log](https://github.com/VeryGoodOpenSource/very_good_templates/actions/runs/9837276486/job/27154736675).

Other publish workflows are also failing due to the same reasons:
- https://github.com/VeryGoodOpenSource/very_good_templates/actions/runs/9837426183/job/27155222822
- https://github.com/VeryGoodOpenSource/very_good_templates/actions/runs/9837476705/job/27155393749
- https://github.com/VeryGoodOpenSource/very_good_templates/actions/runs/9837610493/job/27155793088

**Additional Context**

- The fix https://github.com/VeryGoodOpenSource/very_good_workflows/pull/182, meant to resolve authentication issues with the workflow.

**Requirements**

- [ ] The publish workflow succeeds

**Comment by tomarra** [comment]
Fixed via https://github.com/VeryGoodOpenSource/very_good_templates/pull/207. Documentation also updated with https://github.com/VeryGoodOpenSource/very_good_workflows/pull/263
