### ISSUE TITLE
fix: Update Android App ID in Very Good Wear App

### ISSUE THREAD

**Issue by tomarra** [VeryGoodOpenSource/very_good_templates#156]
**Description**
Need to bring the fix that we did in https://github.com/VeryGoodOpenSource/very_good_templates/pull/148 over to the Very Good Wear App template.

**Requirements**

- [x] The Very Good Wear App is updated to include the fix for the Android App ID
- [x] The output of the template works on an Android device.

**Comment by alestiago** [comment]
Closing as completed by #161 .
