### ISSUE TITLE
very_good did not add {{android_namespace} or {{android_application_id}} in app/build.gradle

### ISSUE THREAD

**Issue by large** [VeryGoodOpenSource/very_good_templates#186]
**Description**
Flame game out-of-the-box did not compile for Android.

**Steps To Reproduce**
Use very_cli 0.22.2 and create a project:
`very_good create flame_game some_game`
> ✓ Generated 343 file(s) (5.8s)
> ✓ Running "flutter pub get" in .  (5.3s)
> ✓ Running "dart fix --apply" in ./some_game (8.4s)
> 
> Created a Very Good Game powered by Flame! 🔥🦄

File generated are missing {{android_namespace} and {{android_application_id}} inn android/app/build.gradle
Needed manually change to same namespace com.example.verygoodcore.some_game, since all other files was changed.

**Expected Behavior**
Compile without any need to change namespace and appID.

**Additional Context**
> [✓] Flutter (Channel stable, 3.24.1, on macOS 14.6.1 23G93 darwin-arm64, locale nb-NO)
> [✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
> [✓] Xcode - develop for iOS and macOS (Xcode 15.4)
> [✓] Chrome - develop for the web
> [✓] Android Studio (version 2024.1)
> [✓] Connected device (4 available)            
> [✓] Network resources
> 
> • No issues found!

**Comment by tomarra** [comment]
Hi @large 👋 Thanks for opening this issue. We are going to attempt to reproduce but could you also ensure you update to the latest Very Good CLI 0.23.0 and retest as well? If either of us are able to reproduce would you be willing to help fix the issue as well?

**Comment by alestiago** [comment]
I was able to reproduce using Very Good CLI 0.23.0, this is indeed a valid issue and should be fixed ASAP.

**Comment by large** [comment]
Also noticed that the lib/gen/assets.gen.dart files are generated by the package https://pub.dev/packages/flutter_gen
But that is not documented into the project out-of-the-box.
Best practice should be to include all assets used.
