### ISSUE TITLE
chore: upgrade to mason v0.1.0

### ISSUE THREAD

**Issue by felangel** [VeryGoodOpenSource/very_good_templates#219]
### Description

There's finally a stable release of `pkg:mason` and `pkg:mason_cli` 🎉 
This issue tracks the work to upgrade all templates so that they support the latest stable version of `mason` and `mason_cli`.

### Requirements

- [ ] Upgrade all templates to support `mason: ^0.1.0` and `mason_cli: ^0.1.0`
- [ ] No functional changes to the code.
- [ ] All CI/CD checks are passing.
- [ ] There is no drop in the test coverage percentage.

**Comment by tomarra** [comment]
Closing as fixed as #218 got merged.
