### ISSUE TITLE
docs: You killed the history of the development

### ISSUE THREAD

**Issue by rekire** [VeryGoodOpenSource/very_good_templates#46]
**Description**

After migrating a couple of issues (42, 43 and 44, which were unnecessary hard to recover the markdown from the GitHub API) I also noticed that you killed the history of the code. It looks now like everything was done by two people in just 4 days. When I look at [`very_good_flutter_plugin`](https://github.com/VeryGoodOpenSource/very_good_flutter_plugin) then there were 8 contributors (bots excluded). Those work is now invisible. I don't like that. There are ways to merge git repositories while keeping the full history. Check for example [this article](https://gfscott.com/blog/merge-git-repos-and-keep-commit-history/). That should have be done out of my view.

**Comment by alestiago** [comment]
Hi @rekire thanks for exposing your concern.

We where aware that the history was going to get killed. However, in reality, there was actually no real meaningful blame history associated with the files that actually got moved. To add some clarity, before, all contributors operated in a "real project", this project was then run through a Bot that after a change in the "real project" it would call a _generator_ script. In essence, this script replaced strings in the "real project" with mustache syntax to create a template (for example, `VeryGoodApp -> {{projectName}}App`). As Mason (the templating language we rely on has improved) and the generator script become more complex and difficult to maintain, we completely removed the Bot from flow:

So we went from: Project -> Generator -> Brick -> Brick Output
To simply: Brick -> Brick Output

Hence, all those `Brick` files we keep today were written by a Bot and the history associated to them was not as meaningful.

I hope this helps 🙌 and I apologize for the inconvenience.

**Comment by rekire** [comment]
In that case [`Co-authored-by:`](https://docs.github.com/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/creating-a-commit-with-multiple-authors) would be an option. This way I also made once a UX-Desginer to a contributor of a private repo.
