### ISSUE TITLE
refactor: deprecate imperative apply of Flutter's Gradle plugins

### ISSUE THREAD

**Issue by alestiago** [VeryGoodOpenSource/very_good_templates#75]
> Note: This issue was originally raised in Very Good CLI by @yuruyuri16 (https://github.com/VeryGoodOpenSource/very_good_cli/issues/968)

**Description**

Since Flutter 3.16, Flutter's Gradle plugins are now applied using the Plugin DSL syntax instead of the legacy script syntax. See the [official migration document](https://docs.flutter.dev/release/breaking-changes/flutter-gradle-plugin-apply).

**Steps To Reproduce**

1. Create a very good flutter app
2. Run in android and some deprecation messages will pop up.

**Expected Behavior**
Run with no warnings.

**Screenshots**
<img width="1435" alt="Screenshot 2024-02-23 at 14 55 57" src="https://github.com/VeryGoodOpenSource/very_good_cli/assets/36353498/dd16a54a-2a2a-426f-9293-183f13166675">

**Requirements**

- [ ] Update all our Android templates that are relying on the imperative apply of Flutter's Gradle Plugins

**Comment by alestiago** [comment]
@yuruyuri16 would you like to take care of `wear_app` and `flame_game` too? If so, I can assign this issue to you entirely.

**Comment by yuruyuri16** [comment]
Sorry for the late response 😥.
The previous version had a kotlin version variable. Is it okay if we keep it?
I found a post which gives a solution: [link](https://stackoverflow.com/questions/38106576/how-do-i-define-a-variable-for-the-dependency-version-in-gradle)

We just need to add a ext block in `android/app/build.gradle`
```
ext {
    kotlinVersion = '1.7.10'
}
```

**Comment by alestiago** [comment]
Hi @yuruyuri16 I'm happy to include the variable you are suggesting to avoid duplicating the Kotlin version. Feel free to open some Pull Request 🙌
